name: booking-reserve

services:
  postgres:
    image: postgres:16
    container_name: postgres-booking

    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - '5433:5432'

    volumes:
      - booking_data:/var/lib/postgresql/data

volumes:
  booking_data:
